name: Report to Codacy Action
author: Michael Beckh
description: Report clang-tidy analysis results to codacy.com.
inputs:
  mode:
    description: Selects the steps to run ('full', 'partial' or 'final', defaults to 'full')
    default: full
  source-dir:
    description: The CMake source directory (defaults to github.workspace)
    default: .
  binary-dir:
    description: The CMake binary directory (defaults to github.workspace)
    default: .
  codacy-token:
    description: The value of the Codacy project token
    required: true
  github-token:
    description: The GitHub token (optional, defaults to github.token)
    default: ${{github.token}}
runs:
  using: node12
  main: ./report.js
