name: Build

on:
  workflow_call:
    outputs:
      commit:
        value: ${{jobs.build.outputs.commit}}

concurrency: 
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build Files in dist/
    runs-on: ubuntu-latest
    outputs:
      commit: ${{steps.licenses.outputs.commit || steps.check.outputs.commit}}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup Node.js v16
      uses: actions/setup-node@v3
      with:
          node-version: 16
    
    - name: Install Modules
      run: npm ci
    
    - name: Build dist/index.js
      run: npm run build
    
    - name: Check for Changes
      id: check
      run: |
        echo "index=$(git status --porcelain=v1 -- dist/index.js | wc -l)" >> $GITHUB_OUTPUT
        echo "licenses=$(git status --porcelain=v1 -- dist/licenses.txt | wc -l)" >> $GITHUB_OUTPUT

    - name: Commit dist/index.js
      if: steps.check.outputs.index
      id: index
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        if sha=$(git rev-parse --quiet --verify ${{github.head_ref || github.ref_name}}:dist/index.js); then
          sha_clause="--field sha=\"$sha\""
        fi
        echo "commit=$(gh api --header 'Accept: application/vnd.github+json' \
          --method PUT /repos/mbeckh/code-quality-actions/contents/dist/index.js \
          --field message="Update dist/index.js for ${{github.sha}}" \
          --field content=@<(base64 -i dist/index.js) \
          --field branch="${{github.head_ref || github.ref_name}}" \
          $sha_clause | jq --raw-output '.commit.sha')" >> $GITHUB_OUTPUT

    - name: Commit dist/licenses.txt
      if: steps.check.outputs.licenses
      id: licenses
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        if sha=$(git rev-parse --quiet --verify ${{github.head_ref || github.ref_name}}:dist/licenses.txt); then
          sha_clause="--field sha=\"$sha\""
        fi
        echo "commit=$(gh api --header 'Accept: application/vnd.github+json' \
          --method PUT /repos/mbeckh/code-quality-actions/contents/dist/licenses.txt \
          --field message="Update dist/licenses.txt for ${{github.sha}}" \
          --field content=@<(base64 -i dist/licenses.txt) \
          --field branch="${{github.head_ref || github.ref_name}}" \
          $sha_clause | jq --raw-output '.commit.sha')" >> $GITHUB_OUTPUT
