name: build

on:
  push:
    branches: [ master, 'feature**' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Test
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup MSVC Environment
      uses: ilammy/msvc-dev-cmd@dd5e2fa0a7de1e7929605d9ecc020e749d9856a3

    - name: Configure
      shell: cmd
      run: cmake -DCMAKE_BUILD_TYPE=Debug -G Ninja -S test -B build

    - name: Build
      shell: cmd
      working-directory: build
      run: cmake --build .

    - name: Coverage
      uses: ./coverage
      with:
        source-dir: test
        binary-dir: build
        codecov: true
        codacy-token: ${{secrets.CODACY_PROJECT_API_TOKEN}}
        github-token: ${{secrets.GITHUB_TOKEN}}

    - name: Report
      uses: ./report
      with:
        source-dir: test
        binary-dir: build
        codacy-token: ${{secrets.CODACY_PROJECT_API_TOKEN}}
        github-token: ${{secrets.GITHUB_TOKEN}}

    - name: Save Logs
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test
        path: |
            build/Testing/**/*.log
            build/clang-tidy-*.log
