name: Build

on:
  push:
    paths:
      - '.github/workflows/build.yml'
      - 'src/**'
      - 'package*'

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build dist/index.js
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup Node.js 16.x
      uses: actions/setup-node@v3
      with:
          node-version: 16.x
    
    - name: Install Modules
      run: npm ci
    
    - name: Build dist/index.js
      run: npm run build
    
    - name: Check dist/index.js
      id: check_index
      shell: bash
      run: |
        count=`git status --porcelain=v1 -- dist/index.js | wc -l`
        echo "changed=$count" >> $GITHUB_OUTPUT

    - name: Check dist/licenses.txt
      id: check_licenses
      shell: bash
      run: |
        count=`git status --porcelain=v1 -- dist/licenses.txt | wc -l`
        echo "changed=$count" >> $GITHUB_OUTPUT

    - name: Commit dist/index.js
      if: steps.check_index.outputs.changed > 0
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        set +e
        sha=$(git rev-parse --quiet --verify ${{github.head_ref || github.ref_name}}:dist/index.js)
        if [ $? -eq 0 ]; then
          sha_clause="--field sha=\"$sha\""
        fi
        set -e
        gh api --method PUT /repos/mbeckh/code-quality-actions/contents/dist/index.js \
          --field message="Update dist/index.js" \
          --field content=@<(base64 -i dist/index.js) \
          --field branch="${{github.head_ref || github.ref_name}}" \
          $sha_clause

    - name: Commit dist/licenses.txt
      if: steps.check_licenses.outputs.changed > 0
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        set +e
        sha=$(git rev-parse --quiet --verify ${{github.head_ref || github.ref_name}}:dist/licenses.txt)
        if [ $? -eq 0 ]; then
          sha_clause="--field sha=\"$sha\""
        fi
        set -e
        gh api --method PUT /repos/mbeckh/code-quality-actions/contents/dist/licenses.txt \
          --field message="Update dist/licenses.txt" \
          --field content=@<(base64 -i dist/licenses.txt) \
          --field branch="${{github.head_ref || github.ref_name}}" \
          $sha_clause
