name: test

on:
  push:
    branches: [ master, 'feature**' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Get Coverage and Perform Static Analysis
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [ Debug, Release ]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup MSVC Environment
      uses:  mbeckh/msvc-dev-cmd@master

    - name: Configure
      shell: cmd
      run: cmake -DCMAKE_BUILD_TYPE=${{matrix.configuration}} -G Ninja -S test -B build

    - name: Build
      shell: cmd
      working-directory: build
      run: cmake --build .

    - name: codecov
      if: matrix.configuration == 'Debug'
      uses: codecov/codecov-action@v2
      with:
        files: build/coverage-*.xml
        fail_ci_if_error: true
        root_dir: test
        verbose: true

    - name: Coverage
      if: matrix.configuration == 'Debug'
      uses: ./coverage
      with:
        source-dir: test
        binary-dir: build
        codecov: true
        codacy-token: ${{secrets.CODACY_PROJECT_API_TOKEN}}

    - name: Report
      uses: ./report
      with:
        mode: partial
        source-dir: test
        binary-dir: build
        codacy-token: ${{secrets.CODACY_PROJECT_API_TOKEN}}

    - name: Save Logs
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: ${{matrix.configuration}}-Logs
        path: |
            build/Testing/**/*.log
            build/clang-tidy-*.log

  final:
    name: Send Completion Message
    runs-on: windows-latest
    needs: build
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Report
      uses: ./report
      with:
        mode: final
        codacy-token: ${{secrets.CODACY_PROJECT_API_TOKEN}}
